### ISSUE TITLE
controller.moveToCalendar无效

### ISSUE THREAD

**Issue by hujianhang2996** [fluttercandies/flutter_custom_calendar#1]
看了一下，貌似原因在于你的monthList里的DateModel的day都是1，而输入的day不为1时targetPage就为-1，函数直接return了，所以其实你的controller只能实现跳到某一月，不能跳到指定的某一天。
这个问题我也在想解决方案，貌似只能在calendar的父widget里加一个“当前选中日期”的state，点击某个按钮时改变这个state再重新build日历视图，不知道你有更好的解决方案没。

**Comment by LXD312569496** [comment]
嗯嗯，刚刚改了一下。现在确实只能实现跳转到某一个月，毕竟只有月视图。
跳转到某一天的话，估计等后面支持周视图的时候一起改一下。
我也再想一下，谢谢你帮忙找出问题哈
