### ISSUE TITLE
设置为多选，最大可选择数量，选择完后，没办法修改已选择的项

### ISSUE THREAD

**Issue by kazeik** [fluttercandies/flutter_custom_calendar#10]
selectMode: Constants.MODE_MULTI_SELECT, 
        maxMultiSelectCount: 2,
然后，选择两个日期 ，再去点击已选择中的一条，没办法取消已选择的项

**Comment by LXD312569496** [comment]
好，我看看

**Comment by LXD312569496** [comment]
最新的代码不会呀，能不能重现一下？

**Comment by LXD312569496** [comment]
嗯嗯，bug已修复。空指针的问题

**Comment by LXD312569496** [comment]
你可以再试试
