### ISSUE TITLE
怎么让日历默认显示周视图?

### ISSUE THREAD

**Issue by yh-demo** [fluttercandies/flutter_custom_calendar#18]
有几个问题请教下!
1.怎么让日历默认显示周视图?就是应用刚打开的时候只显示一行日期，随后用toggleExpandStatus()进行切换?
`

  CalendarController controller;
  @override
  void initState() {
    controller = new CalendarController( showMode: Constants.MODE_SHOW_WEEK_AND_MONTH,);
  }`

2.再次请教一个基本用法，如下改变事件该怎么监听?能否给一个具体点的代码?
`

void addExpandChangeListener(ValueChanged expandChange) | 监听日历的展开收缩状态
-- | --

`

**Comment by LXD312569496** [comment]
1.这个暂时没支持，我改一下。
2.这个我加到readme
尽量明天更新

**Comment by LXD312569496** [comment]
我改了，showMode修改了一下。
  static const int MODE_SHOW_ONLY_MONTH=1;//仅支持月视图
  static const int MODE_SHOW_ONLY_WEEK=2;//仅支持星期视图
  static const int MODE_SHOW_WEEK_AND_MONTH=3;//支持两种视图，先显示周视图
  static const int MODE_SHOW_MONTH_AND_WEEK=4;//支持两种视图，先显示月视图
