### ISSUE TITLE
请问怎么去 动态选中一个日期？

### ISSUE THREAD

**Issue by anfenglei9527** [fluttercandies/flutter_custom_calendar#19]
我这从后台获取出来的数据，返回一个日期  我需要 默认选中这个日期以及在这个日期上标注东西

**Comment by LXD312569496** [comment]
1.等待数据返回后再赋值controller，再显示日历
2.动态设置customExtraData，这个功能我在开发中

**Comment by LXD312569496** [comment]
代码修改了，controller提供了void changeExtraData(Map<DateModel, Object> newMap)方法，随时修改自定义的数据
