### ISSUE TITLE
有个问提 编译打包的时候 报错 昨天更新才出现的

### ISSUE THREAD

**Issue by anfenglei9527** [fluttercandies/flutter_custom_calendar#20]
Error: The getter 'generation' isn't defined for the class 'CalendarProvider'.
 - 'CalendarProvider' is from 'package:flutter_custom_calendar/calendar_provider.dart' ('/D:/flutter/flutter/.pub-cache/git/flutter_custom_calendar-dafc20dd39811fa64b91bc3fe6a3554b2b43f655/lib/calendar_provider.dart').

这个错怎么处理

**Comment by anfenglei9527** [comment]
刚才把最新版下载下来之后controller.dart 文件下的      this.calendarProvider.generation.value++;  报错 程序起不来 

//可以动态修改extraDataMap
  void changeExtraData(Map<DateModel, Object> newMap) {
    this.calendarConfiguration.extraDataMap = newMap;
    this.calendarProvider.generation.value++;
  }

**Comment by LXD312569496** [comment]
嗯嗯，知道原因了，一小部分代码我没上传。。。。

**Comment by LXD312569496** [comment]
嗯，我下午把代码提交上去

**Comment by LXD312569496** [comment]
你可以先把这个generation相关的注释就行了

**Comment by anfenglei9527** [comment]
好的

**Comment by LXD312569496** [comment]
代码上传了，calendar的设置有一点小改动。你可以试试
