### ISSUE TITLE
昨天更新后 获取最新版 默认单选模式 DefaultStylePage 日历表显示 不是自适应了

### ISSUE THREAD

**Issue by anfenglei9527** [fluttercandies/flutter_custom_calendar#22]
日历表显示不是自适应然后 显示出来的 排版不大一样了

**Comment by LXD312569496** [comment]
说的是我的demo还是你的应用？可以加我qq吗，312569496，截图我看看
 

测试唠叨更新签名


 




------------------ 原始邮件 ------------------
发件人: "anfenglei9527"<notifications@github.com>; 
发送时间: 2019年11月1日(星期五) 上午10:30
收件人: "fluttercandies/flutter_custom_calendar"<flutter_custom_calendar@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [fluttercandies/flutter_custom_calendar] 昨天更新后 获取最新版 默认单选模式 DefaultStylePage 日历表显示 不是自适应了 (#22)




日历表显示不是自适应然后 显示出来的 排版不大一样了
 
&mdash;

**Comment by anfenglei9527** [comment]
已解决  我自己程序问题
