### ISSUE TITLE
environment 导致的兼容问题

### ISSUE THREAD

**Issue by mzhipeng** [fluttercandies/flutter_custom_calendar#23]
environment:
  sdk: ">=2.1.0 <3.0.0"

Because every version of flutter_custom_calendar from git depends on provider 3.0.0+1 and education_flutter depends on provider ^3.1.0+1, flutter_custom_calendar from git is forbidden.

**Comment by LXD312569496** [comment]
嗯嗯，这个应该是provider库的冲突，日历用了provider，你的项目也用provider，两个之间冲突了。
我解决了，把我依赖的provider更新到最新版本了，provider: ^3.1.0+1
