### ISSUE TITLE
加入缓存的代码有问题

### ISSUE THREAD

**Issue by xiaozhizhong** [fluttercandies/flutter_custom_calendar#25]
month_view.dart代码中，原逻辑为：
//获取到对应的月份数据，赋值给变量items
getItems();
//紧接着将变量items写入缓存
CacheData.getInstance().monthListCache[firstDayOfMonth] = items;

问题：getItems()是个异步操作，执行getItems()后，执行写入缓存时，此时items还没被赋值数据。
应该为：
//future返回后写入缓存
getItems().then((_){
        CacheData.getInstance().monthListCache[firstDayOfMonth] = items;
      });

**Comment by LXD312569496** [comment]
嗯嗯，对。我把代码改一下，照你说的，提交了。
