### ISSUE TITLE
单选模式下多个日期被选中

### ISSUE THREAD

**Issue by didusmell** [fluttercandies/flutter_custom_calendar#28]
!

**Comment by mcxinyu** [comment]
这个问题比较容易复现，只要切换“周”“月”视图，就会复现。

**Comment by mcxinyu** [comment]
[Screenrecorder-2019-11-22-17-38-29-603.mp4](http://image2.njf2016.com/Screenrecorder-2019-11-22-17-38-29-603.mp4)
把问题录屏演示了

**Comment by mcxinyu** [comment]
然后...好像点得快一点也会复现。

**Comment by LXD312569496** [comment]
嗯嗯，我看看

**Comment by opennflower** [comment]
我也出现这中问题了。点击快一点就会出复现

**Comment by LXD312569496** [comment]
嗯嗯，问题我修复了，自测没重现。你们有空也可以看一下

**Comment by LXD312569496** [comment]
还没处理好，单点触摸的问题我要搞下
