### ISSUE TITLE
1.本月之外的日期可以置灰色，但是如何禁止点击？ 2.如下是我们的需求，如何才能使当前日期之前的日期都置灰？

### ISSUE THREAD

**Issue by NYBingBing** [fluttercandies/flutter_custom_calendar#35]
![6ACF7FF9-181A-46C7-84CF-4D140D60511D](https://user-images.githubusercontent.com/6856641/70419142-d68e6580-1a9f-11ea-95d9-183babec51c9.png)

**Comment by liuxiaoqi1993** [comment]
if(!dateModel.isCurrentMonth){
        return;
      }
![WeChat276d6b0b0aa69789bbe65795768422e2](https://user-images.githubusercontent.com/40969724/70788413-ca6e1500-1dcb-11ea-94b0-a31a4309bd62.png)
