### ISSUE TITLE
你好，请问可以将周六和周日分别在一行的两侧吗？

### ISSUE THREAD

**Issue by bladeofgod** [fluttercandies/flutter_custom_calendar#55]
如题，谢谢，

**Comment by msidolphin** [comment]
@bladeofgod  #54 不确定作者是否合并这个pr，可以暂时先使用我fork的仓库

**Comment by LXD312569496** [comment]
嗯嗯，我这两天看下你的代码，跑一下看看，没问题我再合并

**Comment by bladeofgod** [comment]
> @bladeofgod #54 不确定作者是否合并这个pr，可以暂时先使用我fork的仓库

好的 谢谢 等作者合并吧

**Comment by LXD312569496** [comment]
合并了。那位pull request的兄弟，可以加你微信吗，哈哈

**Comment by bladeofgod** [comment]
> 合并了。那位pull request的兄弟，可以加你微信吗，哈哈

多谢啊 ，不过大佬，接口是啥？

**Comment by msidolphin** [comment]
@bladeofgod  #54 具体的可以看demo

**Comment by bladeofgod** [comment]
> @bladeofgod #54 具体的可以看demo

ok

**Comment by bladeofgod** [comment]
> @bladeofgod #54 具体的可以看demo

你好，我在更新了项目后，设置offset，发现没有效果，请问是什么原因？ 谢谢  
跟自定义 week bar 有关吗？

**Comment by msidolphin** [comment]
@bladeofgod 没有效果是指weekbar还是指日历视图，weekbar需要自定义的

**Comment by bladeofgod** [comment]
> @bladeofgod 没有效果是指weekbar还是指日历视图，weekbar需要自定义的

谢谢回复，设置offset 为1时， weekbar 还是 周一到周日，

**Comment by msidolphin** [comment]
@bladeofgod 需要自定义weekbar
```dart
class CustomStyleWeekBarItem extends BaseWeekBar {
  final List<String> weekList = ["日", "一", "二", "三", "四", "五", "六", ];

  @override
  Widget getWeekBarItem(int index) {
    return new Container(
      child: new Center(
        child: new Text(weekList[index]),
      ),
    );
  }
}

```

**Comment by bladeofgod** [comment]
> @bladeofgod 需要自定义weekbar
> 
> ```dart
> class CustomStyleWeekBarItem extends BaseWeekBar {
>   final List<String> weekList = ["日", "一", "二", "三", "四", "五", "六", ];
> 
>   @override
>   Widget getWeekBarItem(int index) {
>     return new Container(
>       child: new Center(
>         child: new Text(weekList[index]),
>       ),
>     );
>   }
> }
> ```



> @bladeofgod 需要自定义weekbar
> 
> ```dart
> class CustomStyleWeekBarItem extends BaseWeekBar {
>   final List<String> weekList = ["日", "一", "二", "三", "四", "五", "六", ];
> 
>   @override
>   Widget getWeekBarItem(int index) {
>     return new Container(
>       child: new Center(
>         child: new Text(weekList[index]),
>       ),
>     );
>   }
> }
> ```

非常感谢 可以了

**Comment by SunLongbri** [comment]
那下面每一天的数据你们是怎么该的，和日期对不上了。

**Comment by SunLongbri** [comment]
知道了，用偏移量
