### ISSUE TITLE
你好，offset偏移没有效果，请问是什么原因？

### ISSUE THREAD

**Issue by bladeofgod** [fluttercandies/flutter_custom_calendar#59]
如题 ，谢谢 
    controller = new CalendarController(
      offset: 1,
      selectMode: 1 ,
      //selectDateModel: dateModelCache ?? DateModel.fromDateTime(DateTime.now())
    );
调整多次都是原始排序顺序

**Comment by msidolphin** [comment]
1、设置了offset之后，weekbar需要自定义
2、缓存数据也会影响计算内容
