### ISSUE TITLE
单选模式 设置默认选中日期  点击默认选中之外的日期会出现两个选中状态

### ISSUE THREAD

**Issue by zjjjavascript** [fluttercandies/flutter_custom_calendar#64]
![image](https://user-images.githubusercontent.com/26682866/81884245-efa8be80-95c9-11ea-97f1-4a550d6175b8.png)

**Comment by lucasjinreal** [comment]
same

**Comment by Quietly-20201113** [comment]
我clone了库自己更改了单选默认选中的问题,;令人崩溃的是 我在当前月以及下一月选中别的日期时不会出现两个选中状态,但是我进入日历不操作直接到切换到上一月,然后在选中就会出现两个选中状态

**Comment by kkloqin** [comment]
在ItemContainerState的initState() 修改
`@override
  void initState() {
    super.initState();
    dateModel = widget.dateModel;
    isSelected = ValueNotifier(dateModel.isSelected);

    WidgetsBinding.instance.addPostFrameCallback((callback) {
      if (configuration.selectMode == CalendarConstants.MODE_SINGLE_SELECT &&
          dateModel.isSelected) {
        calendarProvider.lastClickItemState = this;
      }
    });
  }`就可以了

**Comment by zjjjavascript** [comment]
> ![84FgBNakH9Ke7MQ.jpg](http://storage.dev.highlands.ltd/doc/backend/84FgBNakH9Ke7MQ.jpg)
