### ISSUE TITLE
显示周模式和月模式时，如何默认收起的时候那一周是当前周

### ISSUE THREAD

**Issue by lucasjinreal** [fluttercandies/flutter_custom_calendar#66]
showMode: CalendarConstants.MODE_SHOW_WEEK_AND_MONTH,

默认收起的周试图是从第一周开始的， 怎么默认到当前周？

**Comment by hqwlkj** [comment]
同问， 现在有个 bug 比如当前周是 8月3日 至 8月9日，结果缺显示成了 8月 10日 至 8月16日了。

**Comment by hqwlkj** [comment]
这样通过 传递的参数 来进行跳转无效

```
// 跳转到指定日期

controller.moveToCalendar(widget.currentDate.year, widget.currentDate.month, widget.currentDate.day);

```

**Comment by lucasjinreal** [comment]
其实最大的问题是 折起显示的那一周不是当前周,而是上一周, 可能的得修改这个代码的一个bug

**Comment by hqwlkj** [comment]
我现在的处理方式为，在切换到周视图的时候自动 执行一下到下一周 `controller.nextPage();//操作日历切换到下一页`

**Comment by lucasjinreal** [comment]
@hqwlkj 看起来没问题吗?

**Comment by hqwlkj** [comment]
你们可以使用这个分支 https://github.com/hqwlkj/flutter_custom_calendar.git  已经修复了这个问题  @jinfagang

**Comment by lucasjinreal** [comment]
@hqwlkj 发起一个pull传到pub.dev?

**Comment by hqwlkj** [comment]
提了可能页没有人合并吧

**Comment by LXD312569496** [comment]
你们验证没问题，我就合并一下。抱歉了，最近比较忙，没维护这个，后续找个时间优化一下&nbsp;

测试唠叨更新签名


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yanghc"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 中午11:58
收件人: "fluttercandies/flutter_custom_calendar"<flutter_custom_calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [fluttercandies/flutter_custom_calendar] 显示周模式和月模式时，如何默认收起的时候那一周是当前周 (#66)





 
提了可能页没有人合并吧

**Comment by hqwlkj** [comment]
> 你们验证没问题，我就合并一下。抱歉了，最近比较忙，没维护这个，后续找个时间优化一下&nbsp; 测试唠叨更新签名 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Yanghc"<notifications@github.com&gt;; 发送时间: 2020年8月24日(星期一) 中午11:58 收件人: "fluttercandies/flutter_custom_calendar"<flutter_custom_calendar@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [fluttercandies/flutter_custom_calendar] 显示周模式和月模式时，如何默认收起的时候那一周是当前周 (#66) 提了可能页没有人合并吧 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的

**Comment by lucasjinreal** [comment]
没问题了，可以merge

**Comment by LXD312569496** [comment]
已合

**Comment by lucasjinreal** [comment]
仔细测了下，貌似在stateless里面有问题（我的是bloc design），以前是toggleexpand只是星期拉起展开不再当前周，现在是直接偶尔调到下一个月了。。。比较尴尬

**Comment by hqwlkj** [comment]
> stateless

这个问题我已经发现并处理了，我会提交新的 PR @LXD312569496 @jinfagang

**Comment by lucasjinreal** [comment]
@hqwlkj 牛逼

**Comment by hqwlkj** [comment]
> @hqwlkj 牛逼

如果急用可以使用 


``` yaml

flutter_custom_calendar:
    git:
      url: https://github.com/hqwlkj/flutter_custom_calendar.git
      ref: '1.0.8'

```

**Comment by jinfagang** [comment]
@hqwlkj 基本上没啥问题了,

issue:

1. 默认周试图, 选择其他日期自定义的Custom的样式不会显示, 展开月试图才会;

**Comment by LXD312569496** [comment]
已合

**Comment by LXD312569496** [comment]
后续我会找个时间优化下，最近没怎么搞

**Comment by tianzhiguo123** [comment]
> 你们可以使用这个分支 https://github.com/hqwlkj/flutter_custom_calendar.git 已经修复了这个问题 @jinfagang

你这个和原来的没区别
