### ISSUE TITLE
isCurrentDay有两天

### ISSUE THREAD

**Issue by mongs** [fluttercandies/flutter_custom_calendar#7]
打印dateModel中的isCurrentDay，今天是2019年8月1日，结果发现8月1日跟8月2日  isCurrentDay都是true

![image](https://user-images.githubusercontent.com/16750315/62275647-f5874600-b474-11e9-81e5-bd58ea25096b.png)

![image](https://user-images.githubusercontent.com/16750315/62275664-ff10ae00-b474-11e9-9979-20a9d2ad0554.png)

**Comment by ashen-23** [comment]
原作者的判断有问题，可以在 `date_utils.dart`文件中修改对应方法即可

```
   /// 是否是今天
  static bool isCurrentDay(int year, int month, int day) {
    return DateTime.now().year == year && DateTime.now().month == month && DateTime.now().day == day;
  }
```

**Comment by LXD312569496** [comment]
好，我这两天去修改一下，谢谢老铁们
