### ISSUE TITLE
能不能根据后台的传值，去渲染指定日期的样式？

### ISSUE THREAD

**Issue by wildcatDownstairs** [fluttercandies/flutter_custom_calendar#8]
比如 10月1日 - 10月7日 [{date: "2019-10-1", status: 'res'}, {date: "2019-10-2", status: 'res'}, ...] 背景色是绿色，10月8日{date: "2019-10-18", status: 'work'}背景色是红色，像这样的。
![530EC963C79171D690CFF2EEB9433651](https://user-images.githubusercontent.com/26499420/62682882-bf574280-b9ef-11e9-9be5-f3e79b120a7a.jpg)

**Comment by LXD312569496** [comment]
应该可以实现的

**Comment by wildcatDownstairs** [comment]
> 应该可以实现的

要是有相关的demo就好了，小前端刚刚接触flutter，插件代码啥的看着有点懵逼，emmmm
