### ISSUE TITLE
月末最后几天无法显示的bug有人修复一下吗？

### ISSUE THREAD

**Issue by lucasjinreal** [fluttercandies/flutter_custom_calendar#80]
月末最后几天无法显示的bug有人修复一下吗？

**Comment by lucasjinreal** [comment]
@fluttercandies
@hqwlkj 
@CaiJingLong

**Comment by hqwlkj** [comment]
@jinfagang  能不能提供一些截图或者样例代码

**Comment by lucasjinreal** [comment]
@hqwlkj 你没有这个问题吗?

月末的时候月试图下,最后几天是没有显示的

**Comment by lucasjinreal** [comment]
最后几天空白:
![image](https://user-images.githubusercontent.com/21303438/95550917-4f51ab80-0a3c-11eb-93c8-fd9177a03a7e.png)

下一页就直接这样了:

![image](https://user-images.githubusercontent.com/21303438/95550957-60022180-0a3c-11eb-9715-bb3ace705ed2.png)

**Comment by lucasjinreal** [comment]
1, 2, 3, 4号缺失

**Comment by hqwlkj** [comment]
demo中不存在这个问题，你是进行视图切换的时候出现的还是怎么出现这个问题的？

**Comment by lucasjinreal** [comment]
@hqwlkj 周试图,demo也有

**Comment by hqwlkj** [comment]
你运行就能看见

**Comment by lucasjinreal** [comment]
@hqwlkj 我运行了了,周试图有bug,你看不到么..

**Comment by fengxiaozi123** [comment]
自定义日历的item就可以吧月前月后处理了。

**Comment by lucasjinreal** [comment]
@fengxiaozi123 没懂，怎么处理？？

**Comment by wobiancao** [comment]
Widget getSelectedWidget(DateModel dateModel) {
    if (!dateModel.isCurrentMonth) {
      return SizedBox();  在视图这里处理不是当月的view
    }
