### ISSUE TITLE
怎么做到单选日期范围

### ISSUE THREAD

**Issue by duangaixin** [fluttercandies/flutter_custom_calendar#84]
现在的功能是多选日期范围，怎么能够一次只能选择一个日期范围呢

**Comment by fengxiaozi123** [comment]
calendarController = new CalendarController(
        showMode: CalendarConstants.MODE_SHOW_ONLY_MONTH,
        // maxYear: DateTime.now().year,
        // maxYearMonth: DateTime.now().month,
        offset: 1,
        selectMode: CalendarSelectedMode.singleSelect,
        selectDateModel: _currDate);
