### ISSUE TITLE
UI线程的问题，不知道能否优化下

### ISSUE THREAD

**Issue by ashen-23** [fluttercandies/flutter_custom_calendar#9]
切换月份的时候，查看Performance overlay，平均每帧渲染的时间过长，各种飘红，试着改了下，效果不明显。对flutter的优化还不太够啊，我再翻翻资料看能不能优化下

**Comment by ashen-23** [comment]
release下貌似能接受。。。

**Comment by LXD312569496** [comment]
嗯嗯，后面肯定要优化下，之前没去注意性能方面的问题
