### ISSUE TITLE
使用provider6.0.0的该如何处理

### ISSUE THREAD

**Issue by sonanis** [fluttercandies/flutter_custom_calendar#94]
正在使用flutter 2.5.1，dart 2.14.2，provider 6.0.0，但是pub get 一直提示flutter_custom_calendar依赖provider 的4.1.3。

Because every version of flutter_custom_calendar depends on provider ^4.1.3 and fm depends on provider ^6.0.0, flutter_custom_calendar is forbidden.
So, because fm depends on flutter_custom_calendar ^1.0.5, version solving failed.
pub get failed (1; So, because fm depends on flutter_custom_calendar ^1.0.5, version solving failed.)

**Comment by ebwood** [comment]
use _**dependency_overrides**_ when you have dependency conflict problems.
```
dependency_overrides:
  provider: ^6.0.1
```

**Comment by sonanis** [comment]
可以了，谢谢
